package in.zeta.enums;

public enum AuditAction {
    // Verification Request Actions
    VERIFICATION_REQUEST_CREATED,
    VERIFICATION_REQUEST_ASSIGNED,
    VERIFICATION_REQUEST_REASSIGNED,
    VERIFICATION_STATUS_CHANGED,

    // Document Actions
    DOCUMENT_UPLOADED,
    DOCUMENT_VIEWED,
    DOCUMENT_DOWNLOADED,
    DOCUMENT_UPDATED,
    DOCUMENT_DELETED,

    // Comment Actions
    COMMENT_ADDED,
    COMMENT_UPDATED,
    COMMENT_DELETED,
    COMMENT_VIEWED,

    // User Actions
    USER_LOGIN,
    USER_LOGOUT,
    ACCESS_DENIED,
    USER_ROLE_CHANGED,
    USER_CREATED,

    // System Events
    NOTIFICATION_SENT,
    NOTIFICATION_READ,
    NOTIFICATION_FAILED,

     STATUS_HISTORY_UPDATED
}