package in.zeta.enums;

public enum NotificationType {
    DOCUMENT_UPLOADED,
    ASSIGNED_TO_OFFICER,
    VERIFICATION_REQUESTED,
    DOCUMENT_UPDATED,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    SENT_BACK_FOR_DETAILS,
    COMMENT_ADDED,
    COMMENT_UPDATED
}